### ISSUE TITLE
undefined method `descendants' for #<Module:0x0000aaab167ce9c8> (NoMethodError)

### ISSUE THREAD

**Issue by tchikuba** [pinnymz/migration_comments#42]
I update Rails from 6.0.4 to 6.1.4.
I face following error.

```
root@827fdc13165b:~/sokudan# bundle exec rails c
/usr/local/bundle/ruby/2.7.0/gems/migration_comments-0.4.1/lib/migration_comments.rb:26:in `block in setup': undefined method `descendants' for #<Module:0x0000aaab167ce9c8> (NoMethodError)
	from /usr/local/bundle/ruby/2.7.0/gems/migration_comments-0.4.1/lib/migration_comments.rb:23:in `each'
	from /usr/local/bundle/ruby/2.7.0/gems/migration_comments-0.4.1/lib/migration_comments.rb:23:in `setup'
	from /usr/local/bundle/ruby/2.7.0/gems/migration_comments-0.4.1/lib/migration_comments.rb:59:in `<main>'
	from /usr/local/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /usr/local/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /usr/local/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /usr/local/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /usr/local/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `block (2 levels) in require'
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `each'
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `block in require'
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `each'
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `require'
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler.rb:174:in `require'
	from /root/sokudan/config/application.rb:21:in `<top (required)>'
	from /usr/local/bundle/ruby/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `require'
	from /usr/local/bundle/ruby/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `preload'
	from /usr/local/bundle/ruby/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
	from /usr/local/bundle/ruby/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
	from /usr/local/bundle/ruby/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
	from /usr/local/bundle/ruby/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
	from /usr/local/bundle/ruby/2.7.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from -e:1:in `<main>'
```

My environments:
- Docker image: ruby:2.7.2

When I downgrade Rails to 6.0.4, no error occurs.

**Comment by pinnymz** [comment]
@tchikuba Rails 5.0 was the last supported version for this gem.  Rails now comes with built in support for comments when using MySQL or PostgreSQL, have you looked into that?
